name: Create Empty Commit

on:
  workflow_dispatch:

jobs:
  empty-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config user.name 'sree-hari-s'
          git config user.email 'sreeharis1999@gmail.com'
          git commit --allow-empty -m "Trigger build"
          git push origin main