name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  maybe-append-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Decide randomly whether to update file
        id: random-check
        run: |
          SHOULD_COMMIT=$((RANDOM % 2))
          echo "commit=$SHOULD_COMMIT" >> $GITHUB_OUTPUT

      - name: Checkout code
        if: steps.random-check.outputs.commit == '1'
        uses: actions/checkout@v4

      - name: Append comment to app.py
        if: steps.random-check.outputs.commit == '1'
        run: |
          echo "# keep alive at $(date -u '+%Y-%m-%d %H:%M UTC')" >> app.py

      - name: Commit and push change
        if: steps.random-check.outputs.commit == '1'
        run: |
          git config user.name 'sree-hari-s'
          git config user.email 'sreeharis1999@gmail.com'
          git commit -am "keep-alive: appended comment to app.py"
          git push origin main
